name: observable_collections
version: 0.5.1+2
homepage: https://github.com/SunnyApp/observable_collections
description: Collections that publish and track changes
environment: 
  sdk: '>=2.6.0 <3.0.0'
dependencies: 
  mobx: ^1.2.1+4
  logging: ^0.11.4
  collection_diff: ^1.0.3
  collection_diff_worker: ^0.4.5
  sunny_dart: ^0.6.0+1
  flutter: 
    sdk: flutter
dev_dependencies: 
  mobx_codegen: ^1.1.2
  flutter_test: 
    sdk: flutter
flutter: null
