name: observable_collections
version: 0.7.1-dev.0
homepage: https://github.com/SunnyApp/observable_collections
description: Collections that publish and track changes
environment: 
  sdk: '>=2.16.0 <3.0.0'
dependencies: 
  mobx: ^2.0.7
  logging: ^1.0.2
  dartxx: ^0.5.5-dev.0
  collection_diff: ^2.0.3+6
  collection_diff_worker: ^0.5.5+7
  sunny_dart: ^0.11.0+8
  flutter: 
    sdk: flutter
dev_dependencies: 
  build_runner: ^2.1.10
  build: ^2.3.0
  mobx_codegen: ^2.0.6
  flutter_test: 
    sdk: flutter

flutter: null
