name: observable_collections
version: 0.7.1
homepage: https://github.com/SunnyApp/observable_collections
description: Collections that publish and track changes
environment: 
  sdk: '>=2.17.0 <3.0.0'
dependencies: 
  mobx: ^2.0.7+5
  logging: ^1.0.2
  collection_diff_worker: 
    git: 
      url: git@github.com:SunnyApp/collection_diff_worker
      ref: trippi_app
  collection_diff: 
    git: 
      url: git@github.com:SunnyApp/collection_diff
      ref: trippi_app
  dartxx: 
    git: 
      url: git@github.com:ericmartineau/dartxx.git
      ref: trippi_app
  sunny_dart: 
    git: 
      url: git@github.com:SunnyApp/sunny_dart
      ref: trippi_app
  flutter: 
    sdk: flutter
dev_dependencies: 
  build_runner: ^2.3.2
  build: ^2.3.0
  mobx_codegen: ^2.0.7
  flutter_test: 
    sdk: flutter
flutter: null
