name: observable_collections
version: 0.7.0+3
homepage: https://github.com/SunnyApp/observable_collections
description: Collections that publish and track changes
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  mobx: ^2.0.5
  logging: ^1.0.2
  dartxx: ^0.5.3+2
  collection_diff: ^2.0.3+6
  collection_diff_worker: ^0.5.5+7
  sunny_dart: ^0.11.0+5
  flutter: 
    sdk: flutter
dev_dependencies: 
  build_runner: ^1.12.2
  build_resolvers: ^2.0.0
  analyzer: ^1.5.0
  build: ^2.0.1
  source_span: ^1.8.1
  dart_style: ^1.3.14
  source_gen: ^0.9.10+4
  mobx_codegen: 
    git: 
      url: https://github.com/mobxjs/mobx.dart
      ref: null_safety
      path: mobx_codegen
  flutter_test: 
    sdk: flutter
dependency_overrides: 
  build_runner: ^1.12.1
  build_resolvers: ^2.0.0
  analyzer: ^1.1.0
  build: ^2.0.0
  source_span: ^1.8.1
  dart_style: ^1.3.14
  source_gen: 
    git: 
      url: https://github.com/simolus3/source_gen
      ref: null-safety
      path: source_gen
flutter: null
