name: observable_collections
version: 0.6.1-nullsafety.5
homepage: https://github.com/SunnyApp/observable_collections
description: Collections that publish and track changes
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  mobx: ^2.0.0-nullsafety.3
  logging: ^1.0.0
  dartxx: ^0.4.5-nullsafety.1
  collection_diff: ^2.0.3+5
  collection_diff_worker: ^0.5.5+4
  sunny_dart: ^0.8.0+7
  flutter: 
    sdk: flutter
dev_dependencies: 
  build_runner: any
  build_resolvers: any
  analyzer: any
  build: any
  source_span: any
  dart_style: any
  source_gen: any
  mobx_codegen: 
    git: 
      url: https://github.com/mobxjs/mobx.dart
      ref: null_safety
      path: mobx_codegen
  flutter_test: 
    sdk: flutter
dependency_overrides: 
  build_runner: ^1.12.1
  build_resolvers: ^2.0.0
  analyzer: ^1.1.0
  build: ^2.0.0
  source_span: ^1.8.1
  dart_style: ^1.3.14
  source_gen: 
    git: 
      url: https://github.com/simolus3/source_gen
      ref: null-safety
      path: source_gen
flutter: null
